wandb_version: 1

batch_size:
  value: 32
context_length:
  value: 256
d_ff:
  value: 1344
d_model:
  value: 512
eval_every:
  value: 50
lr:
  value: 0.004485092660380287
max_steps:
  value: 1000
num_heads:
  value: 16
num_layers:
  value: 4
