_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 2
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 32
context_length:
    value: 256
d_ff:
    value: 1344
d_model:
    value: 512
lr:
    value: 0.001
max_seq_len:
    value: 512
num_heads:
    value: 16
num_layers:
    value: 4
