wandb_version: 1

batch_size:
  value: 64
context_length:
  value: 128
d_ff:
  value: 1024
d_model:
  value: 256
eval_every:
  value: 50
lr:
  value: 9.861369470773964e-05
max_steps:
  value: 500
num_heads:
  value: 8
num_layers:
  value: 4
