wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1754614501
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 14
      - 23
      - 37
      4: 3.11.11
      5: 0.19.9
      8:
      - 2
      - 5
      13: darwin-arm64
batch_size:
  desc: null
  value: 16
context_length:
  desc: null
  value: 128
d_ff:
  desc: null
  value: 1024
d_model:
  desc: null
  value: 256
eval_every:
  desc: null
  value: 100
lr:
  desc: null
  value: 4.65056572691634e-05
max_steps:
  desc: null
  value: 10
num_heads:
  desc: null
  value: 8
num_layers:
  desc: null
  value: 4
