_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.9
            "8":
                - 2
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 16
context_length:
    value: 128
d_ff:
    value: 1024
d_model:
    value: 256
eval_every:
    value: 100
lr:
    value: 0.00564932562240052
max_steps:
    value: 1000
num_heads:
    value: 8
num_layers:
    value: 4
